<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BIKE_STOCK [
<!ELEMENT CATEGORY (#PCDATA)>
<!ELEMENT VARIANT (#PCDATA)>
<!ELEMENT SIZE (#PCDATA)>
<!ELEMENT IN_STOCK (#PCDATA)>
<!ELEMENT BIKE (CATEGORY, VARIANT, SIZE, IN_STOCK)>
<!ELEMENT BIKE_STOCK (BIKE+)>
]>
<BIKE_STOCK> <!-- todo: for now its only mtbs -->
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>A</VARIANT>
		<SIZE>S</SIZE>
		<IN_STOCK>15</IN_STOCK>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>B</VARIANT>
		<SIZE>M</SIZE>
		<IN_STOCK>10</IN_STOCK>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>B</VARIANT>
		<SIZE>S</SIZE>
		<IN_STOCK>5</IN_STOCK>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>C</VARIANT>
		<SIZE>S</SIZE>
		<IN_STOCK>2</IN_STOCK>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
</BIKE_STOCK>