<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BIKE_STOCK [
<!ELEMENT CATEGORY (#PCDATA)>
<!ELEMENT VARIANT (#PCDATA)>
<!ELEMENT SIZE (#PCDATA)>
<!ELEMENT RENTED (#PCDATA)>
<!ELEMENT BIKE (CATEGORY, VARIANT, SIZE, RENTED)>
<!ELEMENT BIKE_STOCK (BIKE+)>
]>
<BIKE_STOCK> <!-- todo: for now its only mtbs -->
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>A</VARIANT>
		<SIZE>S</SIZE>
		<RENTED>15</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>A</VARIANT>
		<SIZE>L</SIZE>
		<RENTED>15</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>MTB</CATEGORY>
		<VARIANT>B</VARIANT>
		<SIZE>M</SIZE>
		<RENTED>10</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>ROAD</CATEGORY>
		<VARIANT>B</VARIANT>
		<SIZE>S</SIZE>
		<RENTED>5</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>ROAD</CATEGORY>
		<VARIANT>A</VARIANT>
		<SIZE>S</SIZE>
		<RENTED>2</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>TOURING</CATEGORY>
		<VARIANT>C</VARIANT>
		<SIZE>L</SIZE>
		<RENTED>2</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
	<BIKE>
		<CATEGORY>ROAD</CATEGORY>
		<VARIANT>C</VARIANT>
		<SIZE>S</SIZE>
		<RENTED>2</RENTED>
		<!--todo: where to put <NEEDSMAINTANANCE>TRUE</NEEDSMAINTANANCE>? -->
	</BIKE>
</BIKE_STOCK>